version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  daphne:
    build: .
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8001 config.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - web
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - daphne

volumes:
  postgres_data:
