name: Deploy to Server

on:
  push:
    branches:
      - main  # 또는 배포하고 싶은 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:


    - name: Send notification to Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Deployment to server is complete!\nRepository: '${{ github.repository }}'\nCommit: '${{ github.sha }}'\nBranch: '${{ github.ref }}'"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}