# name: Deploy to Server

on:
  push:
    branches:
      - whiz-main # 또는 배포하고 싶은 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WHIZ_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.WHIZ_SERVER_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            cd ~/catceo_coin
            git stash
            git switch smdoge-main
            git pull origin smdoge-main
            sudo docker-compose -f docker-compose.yml up --build -d

            sudo docker logs catceo_coin-redis-1 > redis-logs.txt
            sudo docker logs catceo_coin-web-1 > web-logs.txt
            sudo docker logs catceo_coin-daphne-1 > daphne-logs.txt
            sudo docker logs catceo_coin-nginx-1 > nginx-logs.txt

            echo '```' > combined_logs.txt
            echo "Redis Logs:" >> combined_logs.txt
            tail -n 2 redis-logs.txt | sed 's/"/\\"/g' >> combined_logs.txt
            echo "" >> combined_logs.txt
            echo "Web Logs:" >> combined_logs.txt
            tail -n 2 web-logs.txt | sed 's/"/\\"/g' >> combined_logs.txt
            echo "" >> combined_logs.txt
            echo "Daphne Logs:" >> combined_logs.txt
            tail -n 2 daphne-logs.txt | sed 's/"/\\"/g' >> combined_logs.txt
            echo "" >> combined_logs.txt
            echo "Nginx Logs:" >> combined_logs.txt
            tail -n 2 nginx-logs.txt | sed 's/"/\\"/g' >> combined_logs.txt
            echo '```' >> combined_logs.txt

            LOGS_CONTENT=$(cat combined_logs.txt | sed ':a;N;$!ba;s/\n/\\n/g')
            curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"content\": \"$LOGS_CONTENT\"}" \
                ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send notification to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "Deployment to server is complete!\nRepository: '${{ github.repository }}'\nCommit: '${{ github.sha }}'\nBranch: '${{ github.ref }}'"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
